ams-hackers/gbforth

rgbds-hello-world/src/memory.asm

The @ label is broken in the current release of rgbds. Instead, uses a
local \@ label to jump to the beginning of the loop. This is also more
robust as it does not assume the size in bytes of the instructions.
Further info: https://github.com/rednex/rgbds/issues/273

Avoid @ in the lcd_WaitVRAM macro

---

dmgforth.fs
rom.fs

- Compute the complement header
- Uses a more declarative `title:` word to define the title
- Define `$xx` word to specify byte placeholders

A few improvements

---

dmgforth.fs
rom.fs

Added a word similar to `title:` to set the manufacturer code (4 chars). Purpose seems to be a bit unclear but it's probably nice to have _the toolkit_ feature complete.
Also added the address to the `gbgame` word so that the order does not matter.
Experimented a bit with the other 2 values for this field (cgb supported / cgb only) but more of a draft still.

Added manufacturer: word

---

src/asm.fs

Not sure if it makes sense to have an alias for it (since it would still be an immediate value), but I figured it makes the pattern matching / emitting more symmetrical.
If not a good idea, `jr,` should probably still match on `~n` specifically rather than `~nn` (because `e,` would discard the higher part of the byte anyway).

Make ~e alias of ~n

---

Makefile
game.fs
src/asm.fs
src/asm.spec.fs
src/gbhw.fs

`res,` actually takes `b` and `r`, where `b` is an immediate value in the range 0-7 (i.e. a byte).
Simply using `#` and defined `n` (same as `r`) for now in ff16f86, but there might be room for improvement.

Finish decoding StopLCD

---

dmgforth
etc/dmgforth.el
examples/hello-world/hello.fs
lib/gbhw.fs
lib/ibm-font.fs
lib/memory.fs
src/asm.fs
src/cartridge.fs
src/gbhw.fs
src/user.fs

Games are included with only the dmgforth-user vocabulary active. This vocabulary control which words games can use.
The words `[host]` and `[endhost]` allow the user to escape this seal and have full access to the forth vocabulary (*not the dmgforth one directly!*).
Also, restrict the words exposed in the `gb-assembler` vocabulary.

Include games in a sealed vocabulary

---

src/asm.fs

Now that the pattern `nn` is not a multi-type alias, but just the 16
version of it, there is a 1-1 mapping from pattern to types and there
is no need to have n/8 and n/16.
Should we do this?

Unify `n/8` and `n/16` with `nn` again

---

dmgforth
examples/hello-world/hello.fs
lib/gbhw.fs
src/cartridge.fs
src/rom.fs

- Removed everything specific to the hello-worlds example from `cartridge.fs` (and moved to `hello.fs`). Specifically:
- The `title:`
- The `reti,` instructions on top of the header
- The global checksum bytes
- Implemented the `global-checksum` calculation and `fix-global-checksum` word.
- Moved cartridge related constants from `gbhw.fs` to `cartridge.fs` and fixed/cleaned up some incorrect ones.

Refactor cartridge

---

test/test.js

Couldn't get this to work with cpu cycles (so using steps instead), but this can be used to verify the image output of a rom.
~Downside: our `hello.fs` (non-asm) seems to not render "Hello world" anymore :(~ Fixed after rebasing

Visual testing

---

etc/dmgforth.el
examples/hello-world-asm/memory.fs
src/asm.fs
src/primitives.fs

Forward-reference to labels seem too powerful and they make interop between Forth and asm harder. This pull request aims to provide an alternative approach to the current labels in asm.fs
- The words `here<` and `<there` allow for backward references in asm.
- The words `there>` and `>here` for forward references.
- Provide words similar to the ones available in Forth: 
- `begin,` `until,`
- `if,` `then,`
Labels would be maintained as an ordinary constant, allowing back references.
- Migrate all forward-reference to labels to use the new constructs. 
- Delete current labels
In the case of far forward references, the following trick can be used
```forth
there> jp, 
constant long-jump
( no need to keep the value in the stack here )
long-jump >here
```

Alternative to labels in asm.fs

---

examples/hello-world-asm/hello.fs
src/asm.fs

Adds 2 words `named-ref>` and `named-ref<` to be used in combination with `there>` and `here<`.
This removes all forward references from the asm example.
Use for long backward reference:
```forth
here<
named-ref< someName
\ code to jump to
( ... )
someName jp,
```
Use for long forward reference:
```forth
there> jp,
named-ref> someName
( ... )
someName
\ code to jump to

Add named references

---

dmgforth
src/asm.fs
src/cartridge.fs
src/user.fs

Moves the initialisation code (`__start:`) below the code generated by the input-file. This fixes the issue described in #50, where we want to emit an address (the DP) that is updated by the input-file.

Move prelude below input-file

---

examples/hello-world/hello.fs
src/rom.fs
src/user.fs

Updated `rom"` to behave like `s"` (returning `offset u` of the compiled string), which greatly simplifies emitting and referencing the Title string in the example.

Implement s"

---

etc/gbforth.el
src/compiler/codegen.fs
src/compiler/cross.fs
src/compiler/debug.fs
src/compiler/ir.fs
src/header.fs
src/set.fs
src/user.fs

This pull request implements conditionals in the cross compiler.
The key for this are two new IR nodes `IR_NODE_FORK` and `IR_NODE_CONTINUE`. They reference other IR pointers.
For the following colon definition
```forth
: max
2dup < if nip else drop then ;
```
the cross compiler will generate the following IR
```
========== max ( $102A60A78 ) ========== 
[ $7FD942600910 ]
CALL 2dup  ( $102A60A38 )
CALL <  ( $102A58F38 )
0<>IF $7FD942600990 ELSE $7FD9426009B0 
[ $7FD942600990 ]
CALL nip  ( $102A56F98 )
CONTINUE $7FD942600A30 
[ $7FD942600A30 ]
RET
[ $7FD9426009B0 ]
CALL drop  ( $102A56E38 )
CONTINUE $7FD942600A30 
```

Conditionals

---

lib/formatted-output.fs
lib/memory.fs
lib/term.fs
lib/term/formatted-output.fs

Add words `<#` `#` `#s` `#>` and `pad`. Then, use them to implement `.R`
The idea is to remove the commented out the area of sokoban #287  that requires `.R`. However, it doesn't quite work, it seems to be writing somewhere where it shouldn't. The system hangs.
It works on GNU/Forth though, so it could be related to video memory. 
I tried replacing `c!` with a `c!video` version but still couldn't make it work so I open this PR to keep track or it for the future.

Implement simplified pictured output words

---

examples/hello-world-asm/hello.fs
examples/sokoban/sokoban.fs
src/rom.fs
src/user.fs

We exported `<rom` before for being a bit more reusable, but it seems like it would usually be used to do a `rom-move` (maybe a better name is possible) anyway.

Export rom-move instead of <rom

---

lib/core.fs

Remove unneeded [host] and [target] from definition

Simplify TO word

---

Makefile

shasum seems to be more commonly present on macOS. On Linux, the
functionality is provided by sha1sum. Detect which of those is present.

Makefile: use sha1sum when shasum is not available

---

src/compiler/cross.fs
src/utils/errors.fs

This detects unreachable IR nodes and shows an error when trying to compile words/literals to it:
```
test/test-ahead-then.fs:3: Unreachable code:
ahead >>>3<<< 4 5 6 7 then
```
Similarly, the final `return,` (typically compiled by `;`) can be skipped in these definitions too.
Fixes #281

Detect unreachable code

---

docs/limitations.md
lib/core.fs
src/rom.fs
src/user.fs
test/compiler/test-sliteral.fs
test/compiler/test-sliteral.js
test/compiler/test-two-constant.fs

**Current behaviour**
`PARSE ( -- addr u )` is defined to automatically write data into the ROM so the string is accessible at run-time. This means that words like `s"` and the derived `."` can simply compile the 2 returned cells (`addr` and `u`) into the current word definition, and strings will work as expected.
**Issues**
However, this behaviour of `s"` causes issues when using it top-level. For example when building a vector of strings like this:
```forth
CREATE vector
s" hello" mem,
s" world" mem,
: main
vector     5 type   \ expect hello
vector 5 + 5 type ; \ expect world
```
This code works in gforth, but gbforth duplicates the strings and starts appending them to the dictionary pointer which is unintended.
**Solution**
Instead of having `PARSE` automatically move strings to the …

Implement SLiteral and update PARSE
